### PR TITLE
Fixes #200 - Lock react version in bower.json to be 15

### LINKED ISSUE #200: Bower "react" dependencies force breaking changes
react dependencies semver (The semantic versioner for npm) are different between
`bower.json` and `package.json`:
In `bower.json` it sets to `"react": ">=0.15.0"`
In `package.json` it sets to `"react": "^15.0.0",`

This force bower users to use the new release of react (16) which include breaking changes (file structure, .. etc.)

### PR DESCRIPTION
**Pull request by Shuki-L**
This fix if for [#200](https://github.com/ngReact/ngReact/issues/200): Set react dependency in bower.json to be up to minor changes of version 15, same as package.json settings.

This prevent forced switching to react 16 for new installation via bower.

### CODE REVIEW

**Comment by kasperp** [comment]
Thanks

**Comment by Shuki-L** [comment]
@kasperp when are the next release planned to?

**Comment by kasperp** [comment]
I can make a new release with this, but does it matter for this. Is the bower module not installed from Github?

**Comment by Shuki-L** [comment]
Right, but there need to be a tag to follow the [semver](http://semver.org/), and get that fix automatically.
Otherwise you need to specify the branch to get that fix.

**Comment by Shuki-L** [comment]
@kasperp so after the above discussion, when are the next release planned to :) ?

**Comment by kasperp** [comment]
@Shuki-L sorry for the delay there should be a 0.15.1 now

**Pull request merged**
