### PR TITLE
Upgrade to react-15.0

### PR DESCRIPTION
**Pull request by bdwain**
npm test runs fine.

### CODE REVIEW

**Comment by kasperp** [comment]
@bdwain thanks for pull request, given https://facebook.github.io/react/blog/2016/04/08/react-v15.0.1.html should depend on ^15.0.1 instead ?

**Comment by bdwain** [comment]
It should pull in the latest version anyway according to the semver. the ^ specifies >= 15.0.0 < 16.0.0

**Comment by kasperp** [comment]
Right - thanks

**Comment by bdwain** [comment]
thanks @kasperp . any chance you can publish this change soon so it can be used?

**Comment by kasperp** [comment]
Yeah - I'll get a release ready

**Pull request merged**
