### PR TITLE
Flux dispatcher support

### PR DESCRIPTION
**Pull request by lifeofcoding**
I personally love to use ngReact with Flux's Dispatcher & Event Emitter for my hybrid Angular Apps at work to get the best of both worlds. This simply includes the Flux Dispatcher & Event Emitter pre-bundled to include their full functionality, and a tiny edit in ngReact to hook into the dispatcher to automatically call `$digest` on event dispatches, so the user doesn't have to do this themselves on all their callbacks/stores.

I went with passing callbacks & methods as props at first, but this feels so much better when adding a hybrid ngReact component to my Angular apps, in keeping with the spirit of unidirectional data flow, for these components specifically.

If you like this idea, and want it included, let me know if you would rather have a separate file/build that includes Flux Dispatcher & Event Emitter bundled, and one without (Vanilla ngReact). This way the user can decide if they would like to use ngReact with Flux Dispatcher, if they want to use this functionality in combination with ngReact, or without.

Since I love this combination, and I think others would like it too, I put this together, and added the hook, because I would love to be able to install ngReact with bower on my projects, and it automatically keep data-binding working correctly when dispatching events from my components to my controllers/modules, without having to call `$digest` in all my stores or callbacks.

Thank you for this wonderful Angular module!

### CODE REVIEW

**Comment by kasperp** [comment]
@lifeofcoding wow that sounds like a great idea, thanks a lot for the contribution. I'll look through the implementation i the coming days.  👍

**Comment by lifeofcoding** [comment]
@kasperp I also wanted to mention, I was going to just add node's event emitter, and flux to the `package.json` file, and just require it in `ngReact.js` and run Browserify over it in the build task.. but realized you are building it a bit different, and the build task really just runs Uglify, and using Browserify over ngReact currently ends up includes Angular, etc.. in the bundled result, because of lines 10-21, wasn't sure of the reasoning for this, and didn't want to change the way you build, or do things too much, which is why I included Node Event Emitter, and Flux Dispatcher in the source.

**Comment by kasperp** [comment]
Yeah your right the build is a bit of a mess. I would actually prefer to get that sorted out.

**Comment by kasperp** [comment]
@lifeofcoding I like would not to include the EventEmitter and Dispatcher in ngReact. I realize we need to fix the build a little. I can do that but I don't have a lot of free time at the moment so it may take a little while.

If it is something you would like to dig into I would appreciate it, if just hang tight :smile:

**Comment by lifeofcoding** [comment]
@kasperp Yeah! I can do that during my free time here somewhat soon! I'll make sure to require in events, and dispatcher instead of having them bundled with the source, so I'll comment once I update the PR, if you get to it first no harm!

**Comment by kasperp** [comment]
:+1:

**Comment by kasperp** [comment]
I'm closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
