### PR TITLE
fixes #198 and adds better support for one-time bindings

### LINKED ISSUE #198: Using reactDirective service renders components twice
I prefer using the reactDirective service because I get better control over my props, however when I use the reactDirective service, it causes each component to render twice, when values haven't changed.

This is not the behavior when using the react-component directive.

examples:

```js
var HelloComponent = React.createClass({
  propTypes: {
    fname : React.PropTypes.string.isRequired,
    lname : React.PropTypes.string.isRequired
  },
  render: function() {
    console.log('rendered');
    return <span>Hello {this.props.fname} {this.props.lname}</span>;
  }
})
app.value('HelloComponent', HelloComponent);
```
```html
 <react-component name="HelloComponent" props="person" watch-depth="reference"/>
```

Will output: ```rendered``` in the console, but

But when using the directive service:
```js
app.directive('helloComponent', function(reactDirective) {
  return reactDirective(HelloComponent);
});
```

```html
<hello-component fname="person.fname" lname="person.lname" />
```

Will output: 
```
rendered
rendered
```
in the console, meaning the component has rendered twice.

I think this is because the component is being rendered with the default props, and then being re-rendered on $scope watch initialization.

You should be able to get rid of line https://github.com/ngReact/ngReact/blob/master/ngReact.js#L290 while still getting the component to render, and it might fix this problem. Going to try to submit a PR for this later today.

### PR DESCRIPTION
**Pull request by hellsan631**
This fixes multiple renders because of issue #198, and adds better support for one-time bindings.

```
<hello-component fname="::person.fname" lname="::person.lname" watch-depth="one-time"/>
```

As it turns out, issue #198 causes modules to render each time a prop is assigned a watch task. So if there is one prop, it renders 2 times, one initial render, and one for the watch task. Two props cause it to render 3 times, and so-on.

So By adding a watch-depth of ```one-time```, we avoid this issue, by rendering the component only after all prop expressions have been delt with. This really helps us avoid additional re-renders when dealing with lists and components with more props.

I have no clue how to add tests for this. I would really love to, but I just don't know enough about how to test for digest cycle triggers and render triggers without really adding in some jank to the tests. But i think this is a pretty big improvement in initial rendering performance, which is what we want with our react components anyways, right?

Let me know what you think about this pull!

### CODE REVIEW

**Comment by kasperp** [comment]
@hellsan631 thanks looks great - if you could add a test and a description of the feature in the README, we can get this merged 👍

**Comment by torkelo** [comment]
this looks good, also encountered the double rendering when using watchDepth reference

**Comment by torkelo** [comment]
any chance this gets merged?

**Comment by kasperp** [comment]
I think it looks good. I would like some tests around this feature and a description in the README. if you want to have go at that we can get it merged.

**Pull request closed without merging**
